[package]
name = "mws-derive"
version = "0.9.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
license = "MIT"
description = "Derive macros for mws"

[dependencies]
syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"

[lib]
proc-macro = true